<!doctype html>
<html lang="en">
    <head>
        <title><?= $title ?> | <?= $site_name ?></title>
        <?= $helpers->stylesheets
            ->add(get_asset('highlight/styles/nyansapow.css'))
            ->add(get_asset('css/nyansapow.css'))
            ->add(get_asset('css/wiki.css'))
            ->setCombine(true)->setContext('wiki') ?>        
        <?= $helpers->javascripts->add(get_asset('highlight/highlight.pack.js'))->add(get_asset('js/wiki.js'))->setCombine(false)->setContext('wiki') ?>
        <script>hljs.initHighlightingOnLoad();</script>
    </head>
    <body>
        <div id="header">
            <h1><?= $site_name ?></h1>
        </div>
        <div id="body">
            <div id="side">
                <div id="book-toc-wrapper"><?= $helpers->menu($toc)->setCurrentUrl($output) ?></div>
            </div>
            <div id="body-wrapper">
            <?= $body->u() ?>
            </div>
            <div id="footer">
                Generated by nyansapow
            </div>
        </div>
    </body>
</html>