<div id="body<?= $book ? '-book' : '-wiki' ?>" class="body">
    <?php if($book === true): ?>
    <div id="side">
        <div id="book-toc-wrapper"><?= $helpers->menu($toc)->setCurrentUrl($output)->setAlias('toc') ?></div>
    </div>
    <?php endif; ?>
    <div id="body-wrapper">
    <?= $body->u() ?>
    </div>
    <div id="footer">
        Generated by nyansapow
    </div>
</div>
