#!/usr/bin/env php
<?php
error_reporting(E_ALL ^ E_NOTICE);

require "lib/Nyansapow.php";
require "lib/clearice/ClearICE.php";

ClearICE::addOptions(
    array(
        'short' => 'i',
        'long' => 'input',
        'has_value' => true,
        'help' => "specifies where the input files for the wiki are found."
    ),
    array(
        'short' => 'o',
        'long' => 'output',
        'has_value' => true,
        "help" => "specifies where the wiki should be written to"
    ),
    array(
        'short' => 'n',
        'long' => 'name',
        'has_value' => true,
        'help' => 'set the name for the entire wiki.This name would be shown in the header section.'
    ),
    array(
        'short' => 's',
        'long' => 'setup-git-hooks',
        'help' => 'setup the nyansapow git hooks in a bare git repository'
    ),
    array(
        'short' => 'r',
        'long'  => 'git-repo',
        'has_value' => true,
        'help'  => 'specify the location of the git repository'
    )
);

ClearICE::addHelp();
ClearICE::setStrict(true);

$description = <<<EOT
nyansapo wiki generator
James Ekow Abaka Ainooson <jainooson@gmail.com>
        
A simple wiki generator engine to be used for the running of a git backed
wiki. Takes an input of a structured folder and outputs a static web page.


EOT;

ClearICE::setDescription($description);
$options = ClearICE::parse();

if(count($options) == 0)
{
    echo ClearICE::getHelpMessage();
    die();
}
else if(isset($options['setup-git-hooks']))
{
    if(is_writable('hooks') && is_dir('hooks'))
    {

        $home = __DIR__;
        
        $config = <<<EOT
<?php
\$input_directory = "{$options['input']}";
\$output_directory = "{$options['output']}";
\$nyansapow_home = "$home";
EOT;

        copy("$home/git_hooks/post-receive", 'hooks/post-receive');
        file_put_contents('hooks/nyansapow.conf.php', $config);
        chmod('hooks/post-receive', 0755);
    }
    else
    {
        fputs(STDERR, "Please ensure that this is a valid Git repository\n");
    }
    die();
}

try
{
    $nyansapow = Nyansapow::open($options['input'], $options);
    $nyansapow->write($options['output']);
}
catch(NyansapowException $e)
{
    fputs(STDERR, wordwrap("{$e->getMessage()}\nTry `{$argv[0]} --help` for more information.\n"));
}

