#!/usr/bin/env php
<?php
error_reporting(E_ALL ^ E_NOTICE);

require "lib/Nyansapow.php";
require "lib/clearice/ClearICE.php";
require "lib/php-markdown/Michelf/Markdown.php";
require "lib/php-markdown/Michelf/MarkdownExtra.php";
require "lib/mustache/src/Mustache/Autoloader.php";

Mustache_Autoloader::register();

ClearICE::addOptions(
    array(
        'short' => 'i',
        'long' => 'input',
        'has_value' => true,
        'help' => "specifies where the input files for the wiki are found."
    ),
    array(
        'short' => 'o',
        'long' => 'output',
        'has_value' => true,
        "help" => "specifies where the wiki should be written to"
    ),
    array(
        'short' => 'n',
        'long' => 'name',
        'has_value' => true,
        'help' => 'set the name for the entire wiki.This name would be shown in the header section.'
    )
);
ClearICE::addHelp();
ClearICE::setStrict(true);

$description = <<<EOT
nyansapo wiki generator
James Ekow Abaka Ainooson <jainooson@gmail.com>
        
A simple wiki generator engine to be used for the running of a git backed
wiki. Takes an input of a structured folder and outputs a static web page.


EOT;

ClearICE::setDescription($description);
$options = ClearICE::parse();

try{
    $nyansapow = Nyansapow::open($options['input'], $options);
    $nyansapow->write($options['output']);
}
catch(NyansapowException $e)
{
    fputs(STDERR, wordwrap("{$e->getMessage()}\nTry `{$argv[0]} --help` for more information.\n"));
}

