#!/usr/bin/env php
<?php

require "nyansapow.conf.php";
require "$nyansapow_home/lib/Nyansapow.php";

$file = fopen("php://stdin", "r");

while(!feof($file))
{
    $refs = fgets($file);
    // Work only on refs pushed to master
    if(preg_match("/(?<from>[0-9a-f]+) (?<to>[0-9a-f]+) (refs\/heads\/master)/", $refs, $matches))
    {
        if($matches['from'] == '0000000000000000000000000000000000000000')
        {
            echo "Generating the whole wiki\n";
            $wiki = Nyansapow::open($input_directory);
            $wiki->write($output_directory);
        }
        else 
        {
            // Just regenerate files that changed
        }
    }
}

