#!/usr/bin/env php
<?php

require "nyansapow.conf.php";
require "$nyansapow_home/lib/Nyansapow.php";

$stdin = fopen("php://stdin", "r");

while(!feof($stdin))
{
    $refs = fgets($stdin);
    // Work only on refs pushed to master
    if(preg_match("/(?<from>[0-9a-f]+) (?<to>[0-9a-f]+) (refs\/heads\/master)/", $refs, $matches))
    {
        if($matches['from'] == '0000000000000000000000000000000000000000')
        {
            generate_entire_wiki();
        }
        else 
        {
            echo "Updating wiki at `$output_directory`\n";
            exec("git rev-list {$matches['from']}..{$matches['to']}", $revisions);
            $modifiedFiles = array();
            
            foreach($revisions as $revision)
            {
                exec("git show --name-only --pretty=\"format:\" $revision", $files);
                $modifiedFiles = array_merge($modifiedFiles, $files);                
            }
            
            $modifiedFiles = array_unique($modifiedFiles);
            $wiki = Nyansapow::open('nyansapow_wiki', $output_directory, array('name' => $name));
            
            foreach($modifiedFiles as $file)
            {
                if($file == '') continue;
                
                if($file == 'render_all')
                {
                    generate_entire_wiki();
                    break;
                }
                
                if($file == 'copy_assets')
                {
                    $wiki->writeAssets();
                }
                
                echo "Writing $file ...\n";
                
                $dir = dirname($file);
                if($dir != '' && !is_dir($dir))
                {
                    @mkdir("nyansapow_wiki/$dir");
                }
                exec ("git show master:{$file} > nyansapow_wiki/$file");
            }            
            
            $wiki->write($modifiedFiles);            
        }
    }
}

function generate_entire_wiki()
{
    require "nyansapow.conf.php";
    echo "Generating a new wiki at `$output_directory`\n";
    exec("git archive master | tar -x -C nyansapow_wiki");
    $wiki = Nyansapow::open('nyansapow_wiki', $output_directory, array('name' => $name));
    $wiki->write($output_directory);    
}
