<div id="side">
    <div id="namespaces-list">
        <?php 
        $items = [];
        foreach($namespaces as $namespace){
            $items[] = array(
                'label' => "{$namespace['label']}",
                'url' => "{$site_path}{$namespace['path']}index.html",
                'id' => str_replace('\\', '_', $namespace['name'])
            );
        }
        echo $helpers->menu($items)->setCurrentUrl($site_path.$namespace_path. 'index.html');
        ?>
    </div>
    <div id="namespace-items-list">
        <?= t('side_items', array('items' => $namespace['classes'], 'type' => 'Classes', 'site_path' => $site_path, 'path' => $path)) ?>
        <?= t('side_items', array('items' => $namespace['interfaces'], 'type' => 'Interfaces', 'site_path' => $site_path, 'path' => $path)) ?>
    </div>
</div><div id="body" class="body">
    <div id="body-wrapper"><?= $body->unescape() ?></div>
</div>
<div id="footer">
    Generated by <b>Nyansapow</b> with Sources parsed by <b><?= $source_parser ?></b>
</div>